In [ ]:
import matplotlib as mpl
from math import sqrt
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Image 
from scipy.stats import kde 
import seaborn as sns
import pandas as pd
import xlwt
import xlrd
import openpyxl
import sklearn
import mca
import prince
from statsmodels.stats.multicomp import MultiComparison
from scipy.stats import chi2_contingency
from matplotlib import style
from scipy.stats import pearsonr
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [ ]:
datos_total = pd.read_excel(r"C:\Users\Asus\Downloads\Consolidado.xlsx")

In [ ]:
datos_total.head()

In [ ]:
tabla_contingencia = pd.crosstab(datos_total['FECHA INICIAL'], [datos_total['TIPO'], datos_total['SUBTIPO'], datos_total['EDAD'], datos_total['FEMENINO'], datos_total['RANGO DE EDAD']], margins=True)

In [80]:
tabla_contingencia

TIPO                    1                                                  \
SUBTIPO                 1
EDAD                   26    27          28          29    30          31
FEMENINO                1     0     1     0     1     0     0     1     0
RANGO DE EDAD       20-29 20-29 20-29 20-29 20-29 20-29 30-39 30-39 30-39
FECHA INICIAL
2022-01-01 00:00:00     0     0     0     0     0     0     0     0     0
2022-01-02 00:00:00     0     0     0     0     0     0     0     0     0
2022-01-03 00:00:00     0     0     0     0     0     0     0     0     0
2022-01-04 00:00:00     0     0     0     0     0     0     0     0     0
2022-01-05 00:00:00     0     0     0     0     0     0     0     0     0
...                   ...   ...   ...   ...   ...   ...   ...   ...   ...
2022-11-24 00:00:00     0     0     0     0     0     0     0     0     0
2022-11-25 00:00:00     0     0     0     0     0     0     0     0     0
2022-11-27 00:00:00     0     0     0     0     0     0     0     0     0
2022-12-20 00:00:00     0     0     0     0     0     0     0     0     0
All                     2     6     2     4     1     6    13     3    21

TIPO                       ...     2                       4              \
SUBTIPO                    ...    22                      13    21
EDAD                       ...    60    62    63    65    37    42    55
FEMENINO                1  ...     1     0     0     0     0     0     0
RANGO DE EDAD       30-39  ... 60-69 60-69 60-69 60-69 30-39 40-49 50-59
FECHA INICIAL              ...
2022-01-01 00:00:00     0  ...     0     0     0     0     0     0     0
2022-01-02 00:00:00     0  ...     0     0     0     0     0     0     0
2022-01-03 00:00:00     0  ...     0     0     0     0     0     0     0
2022-01-04 00:00:00     1  ...     0     0     0     0     0     0     0
2022-01-05 00:00:00     0  ...     0     0     0     0     0     0     0
...                   ...  ...   ...   ...   ...   ...   ...   ...   ...
2022-11-24 00:00:00     0  ...     0     0     0     0     0     0     0
2022-11-25 00:00:00     0  ...     0     0     0     0     0     0     0
2022-11-27 00:00:00     0  ...     0     0     0     0     0     0     0
2022-12-20 00:00:00     0  ...     0     0     0     0     0     0     0
All                     4  ...     5     1     1     1     1     1     2

TIPO                              All
SUBTIPO
EDAD                   57    58
FEMENINO                0     0
RANGO DE EDAD       50-59 50-59
FECHA INICIAL
2022-01-01 00:00:00     0     0     5
2022-01-02 00:00:00     0     0     2
2022-01-03 00:00:00     0     0     3
2022-01-04 00:00:00     0     0     6
2022-01-05 00:00:00     0     0     5
...                   ...   ...   ...
2022-11-24 00:00:00     0     0     3
2022-11-25 00:00:00     0     0     2
2022-11-27 00:00:00     0     0     1
2022-12-20 00:00:00     0     0     1
All                     2     1  9529

[328 rows x 807 columns]

In [79]:
# Utilizamos la función chi2_contingency para calcular el índice de Chi-cuadrado y el p-valor
chi2, p, dof, expected = chi2_contingency(tabla_contingencia)
# Si el p-valor es menor que 0.05, podemos decir que existe una relación significativa entre las variables
if p < 0.05:
    print("Existe una relación significativa entre las variables (p = {})".format(p))
else:
    print("No existe una relación significativa entre las variables (p = {})".format(p))

Existe una relación significativa entre las variables (p = 1.3515720259648945e-109)

In [ ]:
# Visulazing the distibution of the data for every feature
tabla_contingencia.hist(edgecolor='black', linewidth=3, figsize=(500, 500));

In [ ]:
#graficando 
plot = datos_total['EDAD'].plot(figsize=(600, 200))

In [ ]:
datos_total.describe()

In [ ]:
mca = prince.MCA(
        n_components=2,
        n_iter=3,
        copy=True,
        check_input=True,
        engine='auto',
        random_state=42)
mca = mca.fit(tabla_contingencia)

In [ ]:
coor = mca.plot_coordinates(
        X=tabla_contingencia,
        ax=None,
        figsize=(6, 6),
        show_row_points=True,
        row_points_size=10,
        show_row_labels=False,
        show_column_points=True,
        column_points_size=30,
        show_column_labels=False,
        legend_n_cols=1)
coor.get_figure()

In [ ]:
datos2 = datos_total[['FECHA INICIAL', 'TIPO', 'SUBTIPO', 'EDAD', 'FEMENINO', 'RANGO DE EDAD']]

In [ ]:
mca = prince.MCA()
mca.fit(datos2)

In [ ]:
mca.plot_coordinates(datos2,
                     row_points_alpha=.2,
                     figsize=(10, 10),
                     show_column_labels=True
                    );

In [ ]:
#graficando 
plot = datos_total['EDAD'].plot(figsize=(200, 200))

In [ ]:

mca = prince.MCA(tabla_contingencia)
mca.fit(tabla_contingencia)

In [ ]:
tabla_contingencia2 = pd.crosstab(datos_total['FECHA INICIAL'], [datos_total['EDAD'], datos_total['FEMENINO'], datos_total['RANGO DE EDAD']], margins=True)
tabla_contingencia2